pipeline {
    agent any

    stages {
        stage('Build Test') {
            steps {
                dir('Test') {
                    sh 'mvn clean install'
                }
            }
        }
    }
}
