pipeline {
    agent any

    stages {
        stage('Build SpringCore') {
            steps {
                dir('SpringCore') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }
    }
}
