pipeline {
    agent any

    stages {
        stage('Build SpringNew') {
            steps {
                dir('SpringNew') {
                    sh 'mvn clean install'
                }
            }
        }
    }
}
